### ISSUE TITLE
support the request_headers field in the betteruptime_monitor resource

### ISSUE THREAD

**Issue by glam2000** [BetterStackHQ/deprecated-terraform-provider-betteruptime#4]
The _request_headers_ field has just been added to the API.  It would be good if the betteruptime_monitor resource supported it.
See https://docs.betteruptime.com/api/monitors-api#creating-a-new-monitor

**Comment by simonrozsival** [comment]
We moved the code to a different repository. I recreated the issue in the new repo so I'm closing it here.
